/*******************************************************************************
 * Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#include <string.h>
#include "dlib.h"
#include "dlib-private.h"

void __DLib_Array_Init( void * array, size_t dataSize )
{
    void * data;
    
    ( void )array;
    ( void )dataSize;
    
    if( array == NULL || ( ( __DLib_Array * )array )->data != NULL  )
    {
        return;
    }
    
    data = calloc( dataSize, 25 );
    
    if( data != NULL )
    {
        ( ( __DLib_Array * )array )->data       = data;
        ( ( __DLib_Array * )array )->used       = 0;
        ( ( __DLib_Array * )array )->available  = 25;
        ( ( __DLib_Array * )array )->dataSize   = dataSize;
    }
}

size_t __DLib_Array_GetCount( void * array )
{
    ( void )array;
    
    if( array == NULL )
    {
        return 0;
    }
    
    return ( ( __DLib_Array * )array )->used;
}

void * __DLib_Array_GetValueAtIndex( void * array, size_t i )
{
    char * rawData;
    
    if( array == NULL || i >= ( ( __DLib_Array * )array )->used )
    {
        return NULL;
    }
    
    rawData  = ( ( __DLib_Array * )array )->data;
    rawData += ( ( __DLib_Array * )array )->dataSize * i;
    
    return rawData;
}

void __DLib_Array_InsertCopyOfValue( void * array, void * value )
{
    void * data;
    char * rawData;
    
    if( array == NULL || value == NULL || ( ( __DLib_Array * )array )->data == NULL )
    {
        return;
    }
    
    if( ( ( __DLib_Array * )array )->used == ( ( __DLib_Array * )array )->available )
    {
        data = realloc
        (
            ( ( __DLib_Array * )array )->data,
            ( ( __DLib_Array * )array )->dataSize * ( ( ( __DLib_Array * )array )->available + 25 )
        );
        
        if( data != NULL )
        {
            ( ( __DLib_Array * )array )->data       = data;
            ( ( __DLib_Array * )array )->available += 25;
        }
    }
    
    rawData  = ( ( __DLib_Array * )array )->data;
    rawData += ( ( __DLib_Array * )array )->dataSize * ( ( __DLib_Array * )array )->used;
    
    memcpy( rawData, value, ( ( __DLib_Array * )array )->dataSize );
    
    ( ( __DLib_Array * )array )->used++;
}
